# Example file for controlling loading image and overlay text display
# To activate remove "_example" from filename
# ---------------------------------------------------------------------------------------
# Note: Specify filenames without extension (.jpg will be added internally)
# ---------------------------------------------------------------------------------------

# Overlay title
Title: <b><#00ffff>No Man's Land v1.16 RE2 Beta</color></b> <size=65%><#ffffff>(build 24)</color></size>

# Overlay body (typically multi-line text)
# If commented out, only the title will be displayed
Body: |
  <size=135%><#ffffff><b>November 15:</b></color></size>
  <size=85%>Some of these updates require the <#ffffff>pda readdata</color> console command to apply. May reset mission progress if used.</size>
  <size=85%>•<indent=3%>Added more content for the Legacy (devices, planets, stars, PDA triggers, etc) as part of ongoing updates for the Legacy. Not all will apply to existing save games. See change notes for details.</indent></size>
  <size=85%>•<indent=3%>Added option to turn off many tutorial messages in the Project Eden Settings Menu (F1 - Tutorials - Project Eden Admin).</indent></size>
  <size=85%>•<indent=3%>Added more Empyriopedia tutorial messages.</indent></size>
  <size=85%>•<indent=3%>Added table of contents to the Empyriopedia with web links to Empyrion Buddy.</indent></size>
  <size=85%><#00ff00>Check the Empyriopedia (F1) if you have questions about scenario mechanics.</size>
  <size=85%><#00ff95>No Man's Land November 15 Includes:</size>
  <size=85%>•<indent=3%>Modifed existing and Migrated RE1 Drone Capacitor Matrixes.</indent></size>
  <size=85%>•<indent=3%>Modified existing and Migrated RE1 Hive Nursery's.</indent></size>
  <size=85%>•<indent=3%>Increased hv/sv/cv/ba Aux core CPU outputs.</indent></size>
  <size=85%>•<indent=3%>Corrected Teleporter Tiers so NPC Stations have 75ly by default.</indent></size>
  <size=85%>•<indent=3%>Increased all Hydroponic Bay yields by 20%</indent></size>
  <size=85%>•<indent=3%>Stay tuned for new end game Faction coming soon!</indent></size>
  
# To show a certain image at the start of each loading image sequence, specify the respective file name
# To use the default random image selection, comment out the following line
# FirstPic: p49

# To show the overlay text with certain images only, specify the respective file names
# To show the text with every image, comment out the following line
# ShowWith: [ p02, p03 ]

# Show time for images - if not specified differently below
# If commented out, the default is 10 seconds
# Note: This time depends on the speed of the client computer as when loading a game a lot of work is done in parallel
StandardShowTime: 20

# To set a specific show time for certain images, specify "filename: time" lines
# If not needed, comment out all lines of the following parameter
# ShowTimes:
  # p49: 45
  # p06: 8
